#!/bin/sh

# Démarrage du serveur FTP du programmeur admin.

INITIAL=$PWD
cd $(dirname $0)
FTP_BIN=$(realpath "../../apache-ftpserver/bin/ftpd.sh")
FTP_CONFIG="res/conf/ftpd-typical.xml"

$FTP_BIN $FTP_CONFIG

echo "Fini."
cd $INITIAL