#!/bin/sh

# Publication des implémentations du programmeur admin sur son serveur FTP.

INITIAL=$PWD
cd $(dirname $0)
SOURCE=$(realpath "../../implementation/bin")
DESTINATION=$(realpath "../../implementation/ftp")
FTP=$(realpath "../../apache-ftpserver/res/home")

if [ -d $DESTINATION ]
then
    rm -rf $DESTINATION
fi
mkdir -p $DESTINATION

echo "Copie du service admin.Inversion..."
cp $SOURCE/admin/Inversion.class $DESTINATION/
if [ ! $? -eq 0 ]
then
    echo "La copie du fichier a échoué."
    exit
fi

echo "Copie du service admin.AnalyseXML..."
cp $SOURCE/admin/AnalyseXML.class $DESTINATION/
if [ ! $? -eq 0 ]
then
    echo "La copie du fichier a échoué."
    exit
fi

echo "Création du fichier JAR pour le service admin.Messagerie..."
cd $SOURCE
jar --create --file Messagerie.jar admin/Messagerie.class admin/messagerie
if [ ! $? -eq 0 ]
then
    echo "La création du fichier JAR a échoué."
    exit
fi
mv Messagerie.jar $DESTINATION/Messagerie.jar
if [ ! $? -eq 0 ]
then
    echo "Le déplacement du fichier JAR a échoué."
    exit
fi

echo "Déplacement des binaires sur le serveur FTP..."
cp -r $DESTINATION $FTP/
if [ ! $? -eq 0 ]
then
    echo "Le déplacement sur le serveur a échoué."
    exit
fi

echo "Fini."
cd $INITIAL